name: "global_localization"
version: "0.1.0"
description: "3D-BBS: Global Localization for 3D Point Cloud Scan Matching Using Branch-and-Bound Algorithm"
maintainers:
  - name: "fins"
    email: "fins@sjtu.edu.cn"
depends:
  Eigen3: "3.4.0"
  OpenMP: "system"
  
  geometry_msgs: "system"
  nav_msgs: "system"
  tf2_eigen: "system"

  PCL: "system"
  small_gicp: "1.0.0"

licenses:
  - "MIT"